[package]
name = "graph-lab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my_linked_list = {path = "./my_libs/my_linked_list"}
my_reader = {path = "./my_libs/my_reader"}
